# MySQL. Versions 5.0 and up are supported.
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: 172.28.128.3

development:
  <<: *default
  database: rails5

